name: PHP / Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phpunit:
    name: "PHP ${{ matrix.phpVersion }} / Laravel ${{ matrix.laravelVersion }}"
    runs-on: "ubuntu-24.04"

    strategy:
      fail-fast: false
      matrix:
        include:
          - phpVersion: "8.2"
            laravelVersion: "8.*"
          - phpVersion: "8.2"
            laravelVersion: "9.*"
          - phpVersion: "8.2"
            laravelVersion: "10.*"
          - phpVersion: "8.2"
            laravelVersion: "11.*"
          - phpVersion: "8.2"
            laravelVersion: "12.*"
          - phpVersion: "8.3"
            laravelVersion: "12.*"
          - phpVersion: "8.4"
            laravelVersion: "12.*"
          - phpVersion: "8.5"
            laravelVersion: "12.*"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.phpVersion }}"
          tools: "cs2pr"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Tideways"
        run: |
          echo 'deb [signed-by=/usr/share/keyrings/tideways.gpg] https://packages.tideways.com/apt-packages-main any-version main' | sudo tee /etc/apt/sources.list.d/tideways.list > /dev/null
          wget -qO - 'https://packages.tideways.com/key.gpg' | gpg --dearmor | sudo tee /usr/share/keyrings/tideways.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install tideways-php

      - name: "Install dependencies with Composer"
        run: |
          composer update \
            "illuminate/*:${{ matrix.laravelVersion }}" \
            --with-all-dependencies

      - name: "Run PHPUnit"
        run: "php vendor/bin/phpunit"
